name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore UniversityAPI/UniversityAPI.sln

      - name: Build
        run: dotnet build --no-restore UniversityAPI/UniversityAPI.sln

      - name: Test Integration - API
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~IntegrationTests.ApiIntegrationTests \
            --logger "trx;LogFileName=Integration_Api.trx" \
            --results-directory ./TestResults/IntegrationApi
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Integration - API Results
        uses: actions/upload-artifact@v4
        with:
          name: Integration_Api_TestResults
          path: ./TestResults/IntegrationApi

      - name: Test Integration - Authorization
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~IntegrationTests.AuthorizationTests \
            --logger "trx;LogFileName=Integration_Authorization.trx" \
            --results-directory ./TestResults/IntegrationAuthorization
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Integration - Authorization Results
        uses: actions/upload-artifact@v4
        with:
          name: Integration_Authorization_TestResults
          path: ./TestResults/IntegrationAuthorization

      - name: Test Security - InputValidation
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~SecurityTests.InputValidationTests \
            --logger "trx;LogFileName=Security_InputValidation.trx" \
            --results-directory ./TestResults/SecurityInputValidation
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Security - InputValidation Results
        uses: actions/upload-artifact@v4
        with:
          name: Security_InputValidation_TestResults
          path: ./TestResults/SecurityInputValidation

      - name: Test Unit - Controllers - Auth
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Controllers.AuthControllerTests \
            --logger "trx;LogFileName=Unit_Controllers_Auth.trx" \
            --results-directory ./TestResults/UnitControllersAuth
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Unit - Controllers - Auth Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Controllers_Auth_TestResults
          path: ./TestResults/UnitControllersAuth

      - name: Test Unit - Controllers - University
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Controllers.UniversityControllerTests \
            --logger "trx;LogFileName=Unit_Controllers_University.trx" \
            --results-directory ./TestResults/UnitControllersUniversity
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Unit - Controllers - University Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Controllers_University_TestResults
          path: ./TestResults/UnitControllersUniversity

      - name: Test Unit - Services - TokenService
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Services.TokenServiceTests \
            --logger "trx;LogFileName=Unit_Services_TokenService.trx" \
            --results-directory ./TestResults/UnitServicesTokenService
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Unit - Services - TokenService Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Services_TokenService_TestResults
          path: ./TestResults/UnitServicesTokenService

      - name: Test Unit - Services - UniversityService
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Services.UniversityServiceTests \
            --logger "trx;LogFileName=Unit_Services_UniversityService.trx" \
            --results-directory ./TestResults/UnitServicesUniversityService
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Unit - Services - UniversityService Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Services_UniversityService_TestResults
          path: ./TestResults/UnitServicesUniversityService

      - name: Test Unit - Middleware - ExceptionHandling
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Middleware.ExceptionHandlingMiddlewareTests \
            --logger "trx;LogFileName=Unit_Middleware_ExceptionHandling.trx" \
            --results-directory ./TestResults/UnitMiddlewareExceptionHandling
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          fingerprint: ${{ secrets.fingerprint }}
      - name: Upload Unit - Middleware - ExceptionHandling Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Middleware_ExceptionHandling_TestResults
          path: ./TestResults/UnitMiddlewareExceptionHandling
