name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore UniversityAPI/UniversityAPI.sln

      - name: Build
        run: dotnet build --no-restore UniversityAPI/UniversityAPI.sln

      - name: Run Unit Tests
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests \
            --logger "trx;LogFileName=Unit.trx" \
            --results-directory ./TestResults/Unit \
            --verbosity normal
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          FINGERPRINT: ${{ secrets.FINGERPRINT }}
          Jwt__Issuer: "UniversityAPI"
          Jwt__Audience: "UniversityAPIClient"
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_TestResults
          path: ./TestResults/Unit

      - name: Run Integration Tests
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~IntegrationTests \
            --logger "trx;LogFileName=Integration.trx" \
            --results-directory ./TestResults/Integration \
            --verbosity normal
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          FINGERPRINT: ${{ secrets.FINGERPRINT }}
          Jwt__Issuer: "UniversityAPI"
          Jwt__Audience: "UniversityAPIClient"
      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Integration_TestResults
          path: ./TestResults/Integration

      - name: Run Security Tests
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~SecurityTests \
            --logger "trx;LogFileName=Security.trx" \
            --results-directory ./TestResults/Security \
            --verbosity normal
        env:
          TOPPAN_UNIVERSITYAPI_PUBLIC_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_PUBLIC_KEY }}
          TOPPAN_UNIVERSITYAPI_JWT_KEY: ${{ secrets.TOPPAN_UNIVERSITYAPI_JWT_KEY }}
          TOPPAN_UNIVERSITYAPI_DB_CONNECTION: ${{ secrets.TOPPAN_UNIVERSITYAPI_DB_CONNECTION }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_USERNAME }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_PASSWORD }}
          TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL: ${{ secrets.TOPPAN_UNIVERSITYAPI_ADMIN_INIT_EMAIL }}
          FINGERPRINT: ${{ secrets.FINGERPRINT }}
          Jwt__Issuer: "UniversityAPI"
          Jwt__Audience: "UniversityAPIClient"
      - name: Upload Security Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Security_TestResults
          path: ./TestResults/Security
