name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore UniversityAPI/UniversityAPI.sln

      - name: Build
        run: dotnet build --no-restore UniversityAPI/UniversityAPI.sln

      - name: Test Unit - Controllers
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Controllers \
            --logger "trx;LogFileName=Unit_Controllers.trx" \
            --results-directory ./TestResults/UnitControllers
      - name: Upload Unit - Controllers Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Controllers_TestResults
          path: ./TestResults/UnitControllers

      - name: Test Unit - Services
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Services \
            --logger "trx;LogFileName=Unit_Services.trx" \
            --results-directory ./TestResults/UnitServices
      - name: Upload Unit - Services Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Services_TestResults
          path: ./TestResults/UnitServices

      - name: Test Unit - Middleware
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~UnitTests.Middleware \
            --logger "trx;LogFileName=Unit_Middleware.trx" \
            --results-directory ./TestResults/UnitMiddleware
      - name: Upload Unit - Middleware Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit_Middleware_TestResults
          path: ./TestResults/UnitMiddleware

      - name: Test Integration
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~IntegrationTests \
            --logger "trx;LogFileName=Integration.trx" \
            --results-directory ./TestResults/Integration
      - name: Upload Integration Results
        uses: actions/upload-artifact@v4
        with:
          name: Integration_TestResults
          path: ./TestResults/Integration

      - name: Test Security
        run: |
          dotnet test UniversityAPI.Tests/UniversityAPI.Tests.csproj \
            --filter FullyQualifiedName~SecurityTests \
            --logger "trx;LogFileName=Security.trx" \
            --results-directory ./TestResults/Security
      - name: Upload Security Results
        uses: actions/upload-artifact@v4
        with:
          name: Security_TestResults
          path: ./TestResults/Security
